# /*---------------------------------------------------------------------------8
# |                                                                            |
# |                   Playbook for retrieving the sshkey                       |
# |                                                                            |
# +------------------------------------4--------------------------------------*/
---

- hosts: localhost
  gather_facts: false
  tags:
  - always


  tasks:
  - name: Load the SAP parameters
    include_vars: "{{ _workspace_directory }}/sap-parameters.yaml"


  - name: Retrieve S User secret details
    command: >-
      az keyvault secret show
        --vault-name {{ kv_uri }}
        --name "S-Username"
    changed_when: false
    register: keyvault_secret_show_SUser
    no_log: true


  - name: Extract S User secret details
    set_fact:
      SUser: >-
        {{ (keyvault_secret_show_SUser.stdout | from_json).value }}
    no_log: true

  - name: Show S User
    debug:
      var: SUser

  - name: Retrieve S Password secret details
    command: >-
      az keyvault secret show
        --vault-name {{ kv_uri }}
        --name "S-Password"
    changed_when: false
    register: keyvault_secret_show_SPassword
    no_log: true


  - name: Extract S User Password secret details
    set_fact:
      SPassword: >-
        {{ (keyvault_secret_show_SPassword.stdout | from_json).value }}
    no_log: true


  - name: Retrieve Access Key secret details
    command: >-
      az keyvault secret show
        --vault-name {{ kv_uri }}
        --name "sapbits-access-key"
    changed_when: false
    register: keyvault_secret_show_AccessKey
    no_log: true


  - name: Extract S User Password secret details
    set_fact:
      sapbits_access_key: >-
        {{ (keyvault_secret_show_AccessKey.stdout | from_json).value }}
    no_log: true


...
# /*---------------------------------------------------------------------------8
# |                                   END                                     |
# +------------------------------------4--------------------------------------*/
