# /*----------------------------------------------------------------------------8
# |                                                                            |
# |                      Playbook for HANA DB HSR                          |
# |                                                                            |
# +------------------------------------4--------------------------------------*/
---

# Steps:
#   01) Hana DB system replication 
#

- hosts:          "{{ sap_sid|upper }}_DB"

  name:           DB Installation - HANA
  remote_user:    "{{ orchestration_ansible_user }}"                
  become:         yes
  become_user:    root
  gather_facts:   true
  vars_files:
    - vars/ansible-input-api.yaml                               # API Input template with defaults


  tasks:
# -------------------------------------+---------------------------------------8
#
# Build the list of tasks to be executed in order here. 
#
# -------------------------------------+---------------------------------------8

  - set_fact:
      tier:     hdb                                                             # Actions for HANA DB Servers
      primary_instance_name : "{{ ansible_play_hosts_all[0] }}"                 # Setting up Primary Instance Name 
      secondary_instance_name: "{{ ansible_play_hosts_all[1] }}"                # Setting up Secondary Instance Name


  - include_role:
      name:     roles-db/4.0.1-hdb-hsr
      


...
# /*----------------------------------------------------------------------------8
# |                                    END                                      |
# +------------------------------------4--------------------------------------*/
