# /*----------------------------------------------------------------------------8
# |                                                                            |
# |                         PLAYBOOK FOR BOM DOWNLOADER                        |
# |                                                                            |
# +------------------------------------4--------------------------------------*/
---

# Steps:
#   01) Process BOM (Validate and Extract)
#

- hosts:          localhost

  name:           BOM Downloader
  gather_facts:   false
  connection:     local
  become:         yes
  become_user:    root
 
  vars_files:
    - vars/ansible-input-api.yaml                               # API Input template with defaults


  tasks:
# -------------------------------------+---------------------------------------8
#
# Build the list of tasks to be executed in order here. 
#
# -------------------------------------+---------------------------------------8

  - set_fact:
      tier:     "uploader"

  - include_role:
      name:     roles-sap/0.1-bom-validator


...
# /*---------------------------------------------------------------------------8
# |                                   END                                      |
# +------------------------------------4--------------------------------------*/
