---

#@TODO - To be able to retrieve SPN credentials(Sub id, tenant id, app id and password) from KeyVault
#running current playbook with hardcoded credentials to test the playbooks. 
- name: Check the fencing agent configuration variables are set
  assert:
    that:
      - "sap_hana_fencing_spn_subscription_id is defined"
      - "sap_hana_fencing_spn_subscription_id | trim | length > 0"
      - "sap_hana_fencing_spn_tenant_id is defined"
      - "sap_hana_fencing_spn_tenant_id | trim | length > 0"
      - "sap_hana_fencing_spn_client_id is defined"
      - "sap_hana_fencing_spn_client_id | trim | length > 0"
      - "sap_hana_fencing_spn_client_pwd is defined"
      - "sap_hana_fencing_spn_client_pwd | trim | length > 0"

- name: Check the required cluster password is set
  assert:
    that:
      - "password_ha_db_cluster is defined"
      - "password_ha_db_cluster | trim | length > 0"

- name: Check the required Clustering scripts are available
  when: ansible_os_family == 'Suse'
  stat:
    path: "{{ item }}"
  loop:
    - "/usr/sbin/ha-cluster-init"
    - "/usr/sbin/ha-cluster-join"
  register: cluster_scripts_status_results
  failed_when: not cluster_scripts_status_results.stat.exists

- name: Check if a cluster has already been prepared
  shell: "{{ cluster_status_cmd[ansible_os_family] }}"
  register: cluster_existence_check_result
  changed_when: false
  failed_when: false
